### PR TITLE
Make mso detection work similar to what file/file does

### LINKED ISSUE #400: .zip incorrectly detected as .xlsx possible regression
**Expected MIME type**
application/zip

**Returned MIME type**
application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

**Version of the library you are using**
v1.4.2

**Output of `go version`**
go version go1.20.4 linux/amd64

**Additional context**
Looks very much like #72. If i zip a .xlsx file without compression its still detected as excel file instead of zip. The file utility detects it fine.
```
$ zip -0 test2.zip Book1.xlsx 
updating: Book1.xlsx (stored 0%)
$ file test2.zip
test2.zip: Zip archive data, at least v1.0 to extract, compression method=store
```
Example File: https://filetransfer.io/data-package/pX0B7n1q#link (edited link)

When zipping with compression this library detects the type correctly.

### PR DESCRIPTION
**Pull request by gabriel-vasile**
https://github.com/file/file/blob/7c62d696b06e53fc5be015c41a57513278ac6c54/magic/Magdir/msooxml
The algorithm used by file/file is not 100% percent reliable. For example, a zero compression zip containing a docx will still sometimes be detected as docx instead of zip (it depends on how many files and the order of files in the zip.) There is no way to make mso detection 100% reliable because traversing zip entries can only be done when the central directory entry is available. That's not the case with `mimetype` because it's limited to only reading the header of the file.

Second thing in this PR is removing some test data fixtures. From now, I'll try as much as possible to write regular unit tests without relying on test file fixtures. https://github.com/gabriel-vasile/mimetype/issues/575#issuecomment-2347642574 related #550 #575
closes #400

### CODE REVIEW

File: internal/magic/zip.go [hunk 1]
```diff
@@ -42,50 +42,75 @@ func Zip(raw []byte, limit uint32) bool {
...
-	pkIndex := bytes.Index(in, pkSig)
-	// 30 is the offset of the file name in the header.
-	fNameOffset := pkIndex + 30
-	// end if signature not found or file name offset outside of file.
-	if pkIndex == -1 || fNameOffset > len(in) {
-		return
+
+	if !bytes.HasPrefix(b, pk) {
+		return false
 	}
```
Comment (gabriel-vasile) [inline internal/magic/zip.go:57]:
```suggestion
```
